#+TITLE: Homework 3, Group 13

These notebooks have been forked and adapted from the paper [[https://www.semanticscholar.org/paper/e969aa3422a49152c22f3faf734e4561a2a3cf42][Null It Out: Guarding Protected Attributes by Iterative Nullspace Projection]]. In particular, support for gender debiasing in Persian and racial debiasing in English has been added.

The relevant notebooks are:
- https://github.com/NightMachinery/nullspace_projection/blob/master/notebooks/word_vectors_debiasing.ipynb
  
- https://github.com/NightMachinery/nullspace_projection/blob/master/notebooks/word_vectors_debiasing_race.ipynb

- https://github.com/NightMachinery/nullspace_projection/blob/master/notebooks/word_vectors_debiasing_persian.ipynb

These notebooks evaluate the biases found in embeddings using various metrics and mitigate them and report the results. The embeddings can be from any model, including deep transformers like BERT. The technique works as long as it is applied to the inputs of a linear model, such as the last layer of BERT or logistic regression.

The English gender notebook contains more evaluations. Specifically, it evaluates the true positive rate gap metric for careers. As the data for this evaluation was not available for Persian or racial bias, it was omitted for them.

Other relevant papers:
- [[https://www.semanticscholar.org/paper/Man-is-to-Computer-Programmer-as-Woman-is-to-Word-Bolukbasi-Chang/ccf6a69a7f33bcf052aa7def176d3b9de495beb7][Man is to Computer Programmer as Woman is to Homemaker? Debiasing Word Embeddings]]

- [[https://api.semanticscholar.org/arXiv:1903.03862][Lipstick on a Pig: Debiasing Methods Cover up Systematic Gender Biases in Word Embeddings But do not Remove Them]]
